// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwAOoTNkrkyjVDTkOGE1vKZKq9Wyb5fIo',
    appId: '1:638454338811:web:637a095e194f0561d14c5e',
    messagingSenderId: '638454338811',
    projectId: 'dayflow-4ed72',
    authDomain: 'dayflow-4ed72.firebaseapp.com',
    storageBucket: 'dayflow-4ed72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTmHFJpHitI_AQjir_uACHdz6oBk85QU8',
    appId: '1:638454338811:android:45f146ccff5143fbd14c5e',
    messagingSenderId: '638454338811',
    projectId: 'dayflow-4ed72',
    storageBucket: 'dayflow-4ed72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdWXi7z9OZQ-PVCzzCGj9tvDaSpC1nNwI',
    appId: '1:638454338811:ios:ceeecd01d7bf91dfd14c5e',
    messagingSenderId: '638454338811',
    projectId: 'dayflow-4ed72',
    storageBucket: 'dayflow-4ed72.appspot.com',
    iosClientId: '638454338811-840kas9khnrm5erd56chs74rs40ctdpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.dayflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdWXi7z9OZQ-PVCzzCGj9tvDaSpC1nNwI',
    appId: '1:638454338811:ios:6c4beea36f90bc86d14c5e',
    messagingSenderId: '638454338811',
    projectId: 'dayflow-4ed72',
    storageBucket: 'dayflow-4ed72.appspot.com',
    iosClientId: '638454338811-p4fbj5lo70iden324ah0pcsb7u7le0sv.apps.googleusercontent.com',
    iosBundleId: 'com.example.dayflow.RunnerTests',
  );
}
